spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myhouse24
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
    database: postgresql
    database-platform: postgresql
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8081
  servlet:
    application-display-name: myhouse24_admin

logging:
  file:
    name: logs/myhouse24_admin.log
  level:
    org:
      hibernate: info
      springframework: info
    root: info
  logback:
    rollingpolicy:
      max-file-size: 10MB
